apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: flux-system
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:wfudFC0=,iv:+FFZxTOX0hvhvSku3juEk8HE231ODvg4U1Lmt/APLpQ=,tag:Mr5+HbKKjITMZd/cvMekig==,type:str]
    admin-password: ENC[AES256_GCM,data:66oxHecLR74=,iv:ZRGlX0w48QltEWunWeOB1bsFCo2SaNdwC89mghVK2bY=,tag:ciiHvtO11MfZjmxIopQXOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuelZQMzRmS25SRnNiQ3dj
            dURId0YvR3diRzJqNjV6aXp3QWZ1VWVDMEFFCjNZZ2UrTWJicDExaGFmU0l6aVlo
            cGtMUXJ0SnFDTVJoU045QXJPbFg2YkkKLS0tIHhnUW1yV1doSy8rd3VYell3UlJx
            SWhlQzBnTk1YTmM1OWJDTUpyalJnNUEKOd1tBv2yZONxxHlixI//X5Breg9j01Du
            uULhM3ba9Xtm2PpjS6FAlhJ/UP/UYDuJ/kC2eIYDNRNf6/MX9YockQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n9cv99ewmn862y0yxwhg34mcg6dr4sjyjjkpdw38ngl7ax8fwezq637nwh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T19:04:59Z"
    mac: ENC[AES256_GCM,data:Vw61+G3XhZJvZBVIO0kD+ty6mXJA/SvjC5D1dnvIfKX/16PwRWYItMptva9KvWaL6Ed0tEvboiLIWGZ3Q2opWMwMF1z0f5nbrXp4yfJPybkOGk1npuyCaL1lIhhOZTEMuT6/dBCOrzxdF7Uj7vjtkRCJwWOiDdlQSRyW2K6TA+I=,iv:JF27QIsit9CQnzbdFAuPeHXncwR6GpigUktsyRtmi+Y=,tag:SoxfmMVT184xFUCgcj7YHw==,type:str]
    version: 3.13.1
