apiVersion: v1
kind: Secret
metadata:
    name: boinc-projects-secret
    namespace: boinc
type: Opaque
stringData:
    gui-rpc-password: ENC[AES256_GCM,data:FCUf9UBH14s=,iv:ZzrVlO12ekWCUTXZOBUdMlq5tk9CmhMgbJPdGmN/Ex4=,tag:n721pO7lCGHpwrjh5rTAuA==,type:str]
    account_boinc.bakerlab.org_rosetta.xml: ENC[AES256_GCM,data:nDBFVz67x+SdST2nOpreQCA2TN87if5bK6uG+GxxdAA23xOgYUA4Gwj/Z8WTfu3yBOLMazouz7JnkkuhVJNd/YRasKb/A/H99al4jBlvf6n+BkOhPR8Vhx9gr7O2dqLGEpiVwWQ8s1K3AW4/WuIYK9F2slSq/CAO/nNe64FhqmYA/1OyB9HYRazs9SAp3vgZWzscy+QpBSOsA4fgJpYchcnGlHRu1FI0yZuzq67qG50jQ0S+3ysshHBwNnf8uu2lqug8LfdOMkHROUmgKa4MIor01YlUBe3KNjZak/Pf21mnTXwnWd/+W1mWamO0oRTAuIUrmSrrQnUZlc0ZbwDiSY36vg==,iv:CZQ9a2grX86sUm2uLN51F0F5ooi+H/AZpZC2qHpw63g=,tag:1ADEVwP+esnOSqqPZ7tmaA==,type:str]
    account_einstein.phys.uwm.edu.xml: ENC[AES256_GCM,data:ie+mKQfhW/U+YUtRX6YWyBFBE3hlHDF+ysHIA/ONm8YZbWvBxbnSrvcsFtYbYFpEybRrJmXTik4qUetSYCWlpHZelKXBcahYa+00MDlgmX8LlwVDlvqjbmALSVacMlVwy3YX3PNW8F/iPP9/akT3024HfRUU+fRe8Afv6j0dBzutltLrL4PoCRckjkkUiDX8lvqMne+g1fr8tEmIdkmJTNtLfrUqqn1y0HyH18dNJxQvyJxA1Q/uWxofdWc1iavFW6LO9sZrazTlAB8kjIbdVHW1Tt0jdx7Qfma4JAhf7sOAeiSXilAFIZWwoKMyQAsEhSsw7ve4i1dinkNsADkp,iv:jhPT/KXX6C2U6B9sYpKjDJBvWUHYr1Lbdhs0kUyp+gY=,tag:9K0ehNnYELNnZXDnls1Pbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY2VLVjZPSGJoeW5sQi9z
            S3Q2WVpJVmxnMDlGUVE0UXIzSk9wQSs5clJvCjFYUGVrVXUzdnl6TVpNTjUxeUc4
            UkQwd1dsSllGYTI2UEFvbVdMWTVLTUUKLS0tIDBFbXpiMFB2UldZdHNKOEhpd3VO
            ZmYzWUVUdzFRNTJCVkluNWxvOC9EUk0KRvwu0xQLsOalKfd03TzO10lwm3T6GfE9
            PjDhEL7f5rihF1gaNfG2Xu6J8B3AqBJdCRJk+IDbzlDtUVzBuvavpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n9cv99ewmn862y0yxwhg34mcg6dr4sjyjjkpdw38ngl7ax8fwezq637nwh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T15:27:15Z"
    mac: ENC[AES256_GCM,data:JIwog59a1ABD18d6+1PfOg3hQ+GHD5i9yA2AWTE5MB/YWj4MIID4Kwp6Lr1ZGmigTq8W+kVNzd2oqIImMtOh3rZka/PeF5YbmPaPimsQWhaiGwkbBm+TPgB6JVCwCZWXLi66TQBiUADCpS9NwpzP8prW6VraD+RY7p25/bIv1DE=,iv:dgiPwPef8GJjLPtWdHM2Vh4woukzSJicqfOHcxk0yMA=,tag:SN1QIrG7CpMT+SGGxFFWBQ==,type:str]
    version: 3.13.1
