apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service.yaml
  - daemonset.yaml
  - boinc-projects-secret.yaml
  - netpol.yaml
  - global-prefs-override-configmap.yaml
